-- | Bytecode-to-C translator for the native backend (stage 2).
--
-- Each bytecode function becomes one C function over the runtime's
-- QtValue type; the VM operand stack becomes a per-function C array,
-- jumps become labels and gotos, and calls to user functions become
-- direct C calls (supported builtins route through qt_call_builtin).
--
-- Translation is total over the stage-2 subset and fails with a clear
-- message on instructions and builtins later stages will cover
-- (structs, closures, errors, FFI, async), so unsupported programs
-- error at compile time rather than at runtime -- which is what lets
-- the differential harness (stage 3) treat them as clean skips.
module Compiler.CBackend (emitC) where

import AST.Types.Common
  ( ErrorName (..),
    FuncName (..),
    VarName (..),
    unFieldName,
    unTypeName,
  )
import Compiler.Bytecode
import Data.Char (isAlphaNum, isAscii, ord)
import Data.List (nub)
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import Numeric (showHFloat, showOct)

-- | Translate compiled bytecode into a standalone C translation unit
-- (to be compiled against runtime/quant_runtime.{h,c}).
emitC :: [Bytecode] -> Either String Text
emitC bcs
  | FuncName "main" `notElem` map bytecodeFunction bcs =
      Left "native backend: program has no `main` function"
  | otherwise = do
      let userFns = Set.fromList (map bytecodeFunction bcs)
          captures = capturesOf bcs
      funcs <- mapM (emitFunction userFns captures) bcs
      Right $
        T.unlines $
          [ "/* Generated by glados --native; do not edit. */",
            "#include \"quant_runtime.h\"",
            "#include <stdio.h>",
            "#include <string.h>",
            ""
          ]
            ++ map protoLine bcs
            ++ [""]
            ++ dispatchFn bcs
            ++ funcs
            ++ [ "int main(int argc, char **argv) {",
                 "    qt_set_args(argc, argv);",
                 "    qt_set_dispatch(qf_dispatch);",
                 mainCall,
                 "    return 0;",
                 "}"
               ]
  where
    usesAsync = any (any isAsyncInstr . bytecodeInstructions) bcs
    -- Async programs drive `main` through the cooperative scheduler (as task
    -- 0); everything else calls it directly on the process stack.
    mainCall
      | usesAsync = "    qt_async_run(" <> cString "main" <> ");"
      | otherwise = "    " <> mangle (FuncName "main") <> "(0, (const QtValue *)0);"
    protoLine bc =
      "static QtValue "
        <> mangle (bytecodeFunction bc)
        <> "(size_t argc, const QtValue *args);"

-- | Instructions that require the async runtime (drive `main` via the scheduler).
isAsyncInstr :: Instruction -> Bool
isAsyncInstr (ISpawn _ _) = True
isAsyncInstr IAwait = True
isAsyncInstr _ = False

-- | Resolve an @IDynMethodCall@'s @Type.method@ name to the concrete C
-- function at runtime.  The receiver's struct type + the method name form
-- the key; this if-chain is the native equivalent of the VM's
-- @vmStructTypes@-driven dispatch.
dispatchFn :: [Bytecode] -> [Text]
dispatchFn bcs =
  [ "static QtValue qf_dispatch(const char *name, size_t argc, const QtValue *args) {"
  ]
    ++ [ "    if (strcmp(name, "
           <> cString (unFuncName f)
           <> ") == 0) return "
           <> mangle f
           <> "(argc, args);"
         | f <- map bytecodeFunction bcs
       ]
    ++ [ "    qt_panic(\"native backend: no method for dynamic dispatch\");",
         "}",
         ""
       ]

-- | C identifier for a Quant function name ('.' becomes "__").
mangle :: FuncName -> Text
mangle (FuncName n) = "qf_" <> T.concatMap mangleChar n
  where
    mangleChar '.' = "__"
    mangleChar c
      | isAscii c && isAlphaNum c = T.singleton c
      | otherwise = "_x" <> T.pack (show (ord c)) <> "_"

localName :: VarName -> Text
localName (VarName n) = "l_" <> T.concatMap mangleChar n
  where
    mangleChar '.' = "__"
    mangleChar c
      | isAscii c && isAlphaNum c = T.singleton c
      | otherwise = "_x" <> T.pack (show (ord c)) <> "_"

-- | C string literal with octal escapes for anything non-printable.
cString :: Text -> Text
cString t = "\"" <> T.concatMap esc t <> "\""
  where
    esc '"' = "\\\""
    esc '\\' = "\\\\"
    esc '\n' = "\\n"
    esc '\r' = "\\r"
    esc '\t' = "\\t"
    esc c
      | isAscii c && ord c >= 0x20 && ord c < 0x7f = T.singleton c
      | otherwise = octEsc c
    -- Encode as UTF-8 bytes, each as a fixed-width octal escape (safe
    -- against following digit characters, unlike hex escapes).
    octEsc c = T.concat [T.pack ("\\" ++ pad (showOct b "")) | b <- utf8Bytes (ord c)]
    pad s = replicate (3 - length s) '0' ++ s
    utf8Bytes cp
      | cp < 0x80 = [cp]
      | cp < 0x800 = [0xc0 + cp `div` 64, 0x80 + cp `mod` 64]
      | cp < 0x10000 =
          [0xe0 + cp `div` 4096, 0x80 + (cp `div` 64) `mod` 64, 0x80 + cp `mod` 64]
      | otherwise =
          [ 0xf0 + cp `div` 262144,
            0x80 + (cp `div` 4096) `mod` 64,
            0x80 + (cp `div` 64) `mod` 64,
            0x80 + cp `mod` 64
          ]

-- | Map every closure body to its captured variables (in IMakeClosure
-- order), so the generated function can read them back from qt_env at entry.
capturesOf :: [Bytecode] -> Map.Map FuncName [VarName]
capturesOf bcs =
  Map.fromList
    [ (target, capVars)
      | bc <- bcs,
        IMakeClosure target capVars <- bytecodeInstructions bc
    ]

emitFunction :: Set.Set FuncName -> Map.Map FuncName [VarName] -> Bytecode -> Either String Text
emitFunction userFns captures bc = do
  let fname = bytecodeFunction bc
      instrs = bytecodeInstructions bc
      pool = bytecodeStrings bc
      poolName = "P_" <> mangle fname
      targets = Set.fromList (concatMap jumpTargets instrs)
      locals = nub (concatMap localsOf instrs)
      capVars = Map.findWithDefault [] fname captures
  bodies <- mapM (emitInstr fname userFns poolName) (zip [0 ..] instrs)
  let numbered =
        [ (if Set.member i targets then "  I" <> T.pack (show i) <> ": ;\n" else "")
            <> body
          | (i, body) <- zip [(0 :: Int) ..] bodies
        ]
      poolDef
        | null pool = []
        | otherwise =
            [ "static const char *"
                <> poolName
                <> "[] = {"
                <> T.intercalate ", " (map cString pool)
                <> "};"
            ]
  Right $
    T.unlines $
      poolDef
        ++ [ "static QtValue " <> mangle fname <> "(size_t argc, const QtValue *args) {",
             "  (void)argc; (void)args;",
             "  QtValue st[" <> T.pack (show (length instrs + 8)) <> "];",
             "  size_t sp = 0;"
           ]
        ++ ["  QtValue " <> localName v <> " = qt_unit();" | v <- locals]
        ++ ["  (void)" <> localName v <> ";" | v <- locals]
        ++ [ "  for (size_t qi = argc; qi > 0; qi--) { st[sp++] = args[qi - 1]; }"
           ]
        -- Seed captured locals from the bound closure environment (stage 7).
        ++ [ "  " <> localName v <> " = qt_env(" <> T.pack (show i) <> ");"
             | (i, v) <- zip [(0 :: Int) ..] capVars
           ]
        ++ numbered
        ++ [ "  return qt_unit();",
             "}"
           ]

jumpTargets :: Instruction -> [Int]
jumpTargets (IJump (InstructionPointer t)) = [t]
jumpTargets (IJumpTrue (InstructionPointer t)) = [t]
jumpTargets (IJumpFalse (InstructionPointer t)) = [t]
jumpTargets _ = []

localsOf :: Instruction -> [VarName]
localsOf (ILoad v) = [v]
localsOf (IStore v) = [v]
localsOf _ = []

binOpName :: BinaryOp -> Text
binOpName op = case op of
  BOpAdd -> "QT_BOP_ADD"
  BOpSub -> "QT_BOP_SUB"
  BOpMul -> "QT_BOP_MUL"
  BOpDiv -> "QT_BOP_DIV"
  BOpMod -> "QT_BOP_MOD"
  BOpEq -> "QT_BOP_EQ"
  BOpNeq -> "QT_BOP_NEQ"
  BOpLt -> "QT_BOP_LT"
  BOpLte -> "QT_BOP_LTE"
  BOpGt -> "QT_BOP_GT"
  BOpGte -> "QT_BOP_GTE"
  BOpAnd -> "QT_BOP_AND"
  BOpOr -> "QT_BOP_OR"
  BOpBitAnd -> "QT_BOP_BITAND"
  BOpBitOr -> "QT_BOP_BITOR"
  BOpBitXor -> "QT_BOP_BITXOR"
  BOpShl -> "QT_BOP_SHL"
  BOpShr -> "QT_BOP_SHR"

unOpName :: UnaryOp -> Text
unOpName UOpNot = "QT_UOP_NOT"
unOpName UOpNeg = "QT_UOP_NEG"
unOpName UOpBitNot = "QT_UOP_BITNOT"

pushConst :: Text -> Text
pushConst expr = "  st[sp++] = " <> expr <> ";"

-- | Builtins qt_call_builtin implements (keep in sync with the runtime).
-- Calls to any other non-user function fail at translation time so the
-- differential harness can classify them as skips, not runtime diffs.
supportedBuiltins :: Set.Set Text
supportedBuiltins =
  Set.fromList $
    [ "print",
      "println",
      "io.print",
      "io.println",
      "len",
      "array.len",
      "push",
      "array.push",
      "pop",
      "array.pop",
      "dict.has",
      "dict.len",
      "dict.delete"
    ]
      ++ map ("string." <>) stringBuiltins
      ++ map ("math." <>) mathBuiltins
      ++ map ("sys." <>) sysBuiltins
      ++ map ("file." <>) fileBuiltins
      ++ map ("buf." <>) bufBuiltins
      ++ map ("ptr." <>) ptrBuiltins

-- | string.* builtins the C runtime implements (stage 4).  Excludes
-- `hash`, whose VM definition folds over unbounded Integers.
stringBuiltins :: [Text]
stringBuiltins =
  [ "to_str",
    "concat",
    "from_int",
    "from_float",
    "len",
    "is_empty",
    "substring",
    "char_at",
    "contains",
    "starts_with",
    "ends_with",
    "index_of",
    "last_index_of",
    "to_upper",
    "to_lower",
    "trim",
    "trim_left",
    "trim_right",
    "reverse",
    "replace",
    "replace_first",
    "repeat",
    "to_int",
    "to_float",
    "split",
    "join",
    "format"
  ]

-- | math.* builtins the C runtime implements (stage 4).
mathBuiltins :: [Text]
mathBuiltins =
  [ "sqrt",
    "abs",
    "fabs",
    "floor",
    "ceil",
    "round",
    "exp",
    "log",
    "log2",
    "log10",
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "pow",
    "atan2",
    "min",
    "max",
    "fmin",
    "fmax",
    "pi",
    "tau"
  ]

-- | sys.* builtins the C runtime implements (stage 4).  `sys.args`/`argc`
-- are included but are not output-diffable under the harness: the VM sees
-- the host `glados` process arguments while the native binary sees its own.
sysBuiltins :: [Text]
sysBuiltins =
  [ "exit",
    "write",
    "read",
    "open",
    "close",
    "flush",
    "isatty",
    "stdin_fd",
    "stdout_fd",
    "stderr_fd",
    "o_rdonly",
    "o_wronly",
    "o_rdwr",
    "o_creat",
    "o_trunc",
    "o_append",
    "time",
    "time_millis",
    "sleep",
    "argc",
    "args",
    "env",
    "set_env",
    "platform",
    "hostname",
    "getcwd",
    "chdir",
    "system"
  ]

-- | file.* builtins the C runtime implements (stage 4).
fileBuiltins :: [Text]
fileBuiltins =
  [ "read",
    "write",
    "append",
    "exists",
    "delete",
    "rename",
    "size",
    "lines"
  ]

-- | ptr.* raw-memory builtins the C runtime implements (stage 8).
ptrBuiltins :: [Text]
ptrBuiltins =
  [ "null",
    "is_null",
    "to_int",
    "from_int",
    "add",
    "read_int32",
    "write_int32",
    "read_int64",
    "write_int64",
    "read_float64",
    "write_float64"
  ]

-- | buf.* builtins the C runtime implements (stage 4).
bufBuiltins :: [Text]
bufBuiltins =
  [ "new",
    "write",
    "writeln",
    "to_str",
    "len",
    "clear",
    "flush"
  ]

emitInstr :: FuncName -> Set.Set FuncName -> Text -> (Int, Instruction) -> Either String Text
emitInstr fname userFns poolName (idx, instr) = case instr of
  IPush v -> pushValue v
  IPop -> ok "  sp--;"
  IDup -> ok "  st[sp] = st[sp - 1]; sp++;"
  IBinary op ->
    ok $ "  st[sp - 2] = qt_binary(" <> binOpName op <> ", st[sp - 2], st[sp - 1]); sp--;"
  IUnary op ->
    ok $ "  st[sp - 1] = qt_unary(" <> unOpName op <> ", st[sp - 1]);"
  ILoad v -> ok $ "  st[sp++] = " <> localName v <> ";"
  IStore v -> ok $ "  " <> localName v <> " = st[--sp];"
  IJump (InstructionPointer t) -> ok $ "  goto I" <> T.pack (show t) <> ";"
  IJumpTrue (InstructionPointer t) ->
    ok $ "  if (qt_truthy(st[--sp])) goto I" <> T.pack (show t) <> ";"
  IJumpFalse (InstructionPointer t) ->
    ok $ "  if (!qt_truthy(st[--sp])) goto I" <> T.pack (show t) <> ";"
  ICall (FunctionRef target) argc
    | Set.member target userFns || Set.member (unFuncName target) supportedBuiltins ->
        ok (emitCall target argc)
    | otherwise ->
        Left $
          "native backend: unsupported builtin `"
            ++ T.unpack (unFuncName target)
            ++ "` (in function `"
            ++ T.unpack (unFuncName fname)
            ++ "` at offset "
            ++ show idx
            ++ ")"
  IRet -> ok "  return st[--sp];"
  INop -> ok "  ;"
  ICovMark _ -> ok "  ;"
  ICovBranch _ -> ok "  ;"
  INewArray -> ok "  st[sp++] = qt_array_new();"
  INewDict -> ok "  st[sp++] = qt_dict_new();"
  IArrayGet ->
    ok $
      "  { QtValue qidx = st[--sp]; QtValue qref = st[--sp];"
        <> " st[sp++] = qt_index_get(qref, qidx); }"
  IArrayGetOrNew ->
    ok $
      "  { QtValue qidx = st[--sp]; QtValue qref = st[--sp];"
        <> " st[sp++] = qt_array_get_or_new(qref, qt_want_int(qidx, \"array index\")); }"
  IArraySet ->
    ok $
      "  { QtValue qv = st[--sp]; QtValue qidx = st[--sp]; QtValue qref = st[--sp];"
        <> " qt_index_set(qref, qidx, qv); }"
  ICast CastToInt -> ok "  st[sp - 1] = qt_cast_int(st[sp - 1]);"
  ICast CastToFloat -> ok "  st[sp - 1] = qt_cast_float(st[sp - 1]);"
  ICast CastToBool -> ok "  st[sp - 1] = qt_cast_bool(st[sp - 1]);"
  ICast CastToString -> ok "  st[sp - 1] = qt_cast_string(st[sp - 1]);"
  INewStruct tname ->
    ok $ "  st[sp++] = qt_struct_new(" <> cString (unTypeName tname) <> ");"
  IFieldGet fld ->
    ok $
      "  st[sp - 1] = qt_field_get(st[sp - 1], " <> cString (unFieldName fld) <> ");"
  IFieldSet fld ->
    ok $
      "  { QtValue qv = st[--sp]; QtValue qref = st[--sp];"
        <> " qt_struct_set(qref, "
        <> cString (unFieldName fld)
        <> ", qv); }"
  INewError (ErrorName ename) fnames -> ok (emitNewError ename fnames)
  ITryOp -> ok "  if (qt_is_error(st[sp - 1])) return st[sp - 1];"
  IMustOp -> ok "  qt_must(st[sp - 1]);"
  IIsOk -> ok "  st[sp] = qt_bool(!qt_is_error(st[sp - 1])); sp++;"
  IIsErr (ErrorName ename) ->
    ok $ "  st[sp] = qt_bool(qt_error_is(st[sp - 1], " <> cString ename <> ")); sp++;"
  IDynMethodCall mname argc -> ok (emitDynCall mname argc)
  ILoadFunc target ->
    ok $ "  st[sp++] = qt_fn(" <> cString (unFuncName target) <> ");"
  IMakeClosure target capVars -> ok (emitMakeClosure target capVars)
  ICallIndirect argc -> ok (emitCallIndirect argc)
  ICallFFI lib sym retTy argc -> ok (emitFFI lib sym retTy argc)
  ISpawn (FunctionRef target) argc -> ok (emitSpawn target argc)
  IAwait -> ok "  st[sp - 1] = qt_await(st[sp - 1]);"
  where
    ok = Right
    pushValue v = case v of
      VInt n -> ok $ pushConst ("qt_int(INT64_C(" <> T.pack (show n) <> "))")
      VFloat f -> ok $ pushConst ("qt_float(" <> T.pack (showHFloat f "") <> ")")
      VBool True -> ok $ pushConst "qt_bool(1)"
      VBool False -> ok $ pushConst "qt_bool(0)"
      VStringRef i -> ok $ pushConst ("qt_string(" <> poolName <> "[" <> T.pack (show i) <> "])")
      VString s -> ok $ pushConst ("qt_string(" <> cString s <> ")")
      VUnit -> ok $ pushConst "qt_unit()"
      _ ->
        Left $
          "native backend: unsupported constant "
            ++ takeWhile (/= ' ') (show v)
            ++ " in function `"
            ++ T.unpack (unFuncName fname)
            ++ "`"
    emitCall target argc =
      let nText = T.pack (show argc)
          bufLen = T.pack (show (max 1 argc))
          gather =
            "QtValue ca["
              <> bufLen
              <> "];"
              <> " for (size_t qi = 0; qi < "
              <> nText
              <> "; qi++) { ca[qi] = st[--sp]; }"
          callExpr
            | Set.member target userFns = mangle target <> "(" <> nText <> ", ca)"
            | otherwise =
                "qt_call_builtin(" <> cString (unFuncName target) <> ", " <> nText <> ", ca)"
       in "  { " <> gather <> " st[sp++] = " <> callExpr <> "; }"
    -- Build a VErrorVal: field values were pushed in fnames order, so the
    -- last field's value is on top -- pop and assign in reverse.
    emitNewError ename fnames =
      let assigns =
            [ " qt_error_set_field(qe, " <> cString (unFieldName f) <> ", st[--sp]);"
              | f <- reverse fnames
            ]
       in "  { QtValue qe = qt_error_new("
            <> cString ename
            <> ");"
            <> T.concat assigns
            <> " st[sp++] = qe; }"
    -- Dynamic dispatch: the receiver (self) was pushed last, so it is ca[0].
    -- Its struct type plus the method name resolve the concrete function.
    emitDynCall mname argc =
      let nText = T.pack (show argc)
          bufLen = T.pack (show (max 1 argc))
       in "  { QtValue ca["
            <> bufLen
            <> "]; for (size_t qi = 0; qi < "
            <> nText
            <> "; qi++) { ca[qi] = st[--sp]; }"
            <> " char qn[256];"
            <> " snprintf(qn, sizeof(qn), \"%s."
            <> mname
            <> "\", qt_struct_type(ca[0]));"
            <> " st[sp++] = qf_dispatch(qn, "
            <> nText
            <> ", ca); }"
    -- Package a lambda's captured locals (in capture order) into a closure.
    emitMakeClosure target capVars =
      let nCaps = T.pack (show (length capVars))
          bufLen = T.pack (show (max 1 (length capVars)))
          assigns =
            [ " qc[" <> T.pack (show i) <> "] = " <> localName v <> ";"
              | (i, v) <- zip [(0 :: Int) ..] capVars
            ]
       in "  { QtValue qc["
            <> bufLen
            <> "];"
            <> T.concat assigns
            <> " st[sp++] = qt_closure("
            <> cString (unFuncName target)
            <> ", "
            <> nCaps
            <> ", qc); }"
    -- Indirect call: the callable sits just below the argc arguments.
    emitCallIndirect argc =
      let nText = T.pack (show argc)
          bufLen = T.pack (show (max 1 argc))
       in "  { QtValue ca["
            <> bufLen
            <> "]; for (size_t qi = 0; qi < "
            <> nText
            <> "; qi++) { ca[qi] = st[--sp]; }"
            <> " QtValue qcl = st[--sp];"
            <> " qt_callable_bind(qcl);"
            <> " st[sp++] = qf_dispatch(qt_callable_name(qcl), "
            <> nText
            <> ", ca); }"
    -- Foreign call: marshal args, then dispatch through the runtime FFI shim.
    emitFFI lib sym retTy argc =
      let nText = T.pack (show argc)
          bufLen = T.pack (show (max 1 argc))
          retCode = case retTy of
            CRetVoid -> "0"
            CRetInt -> "1"
            CRetFloat -> "2"
            CRetStr -> "3"
            CRetBool -> "4"
            CRetPtr -> "5"
       in "  { QtValue ca["
            <> bufLen
            <> "]; for (size_t qi = 0; qi < "
            <> nText
            <> "; qi++) { ca[qi] = st[--sp]; }"
            <> " st[sp++] = qt_ffi_call("
            <> cString lib
            <> ", "
            <> cString sym
            <> ", "
            <> retCode
            <> ", "
            <> nText
            <> ", ca); }"
    -- Spawn an async task: queue the function without transferring control.
    emitSpawn target argc =
      let nText = T.pack (show argc)
          bufLen = T.pack (show (max 1 argc))
       in "  { QtValue ca["
            <> bufLen
            <> "]; for (size_t qi = 0; qi < "
            <> nText
            <> "; qi++) { ca[qi] = st[--sp]; }"
            <> " st[sp++] = qt_spawn("
            <> cString (unFuncName target)
            <> ", "
            <> nText
            <> ", ca); }"
