-- | Bytecode-to-C translator for the native backend (stage 2).
--
-- Each bytecode function becomes one C function over the runtime's
-- QtValue type; the VM operand stack becomes a per-function C array,
-- jumps become labels and gotos, and calls to user functions become
-- direct C calls (anything else routes through qt_call_builtin).
--
-- Translation is total over the stage-2 subset and fails with a clear
-- message on instructions later stages will cover (structs, closures,
-- errors, FFI, async), so unsupported programs error at compile time
-- rather than at runtime.
module Compiler.CBackend (emitC) where

import AST.Types.Common (FuncName (..), VarName (..))
import Compiler.Bytecode
import Data.Char (isAlphaNum, isAscii, ord)
import Data.List (nub)
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import Numeric (showHFloat, showOct)

-- | Translate compiled bytecode into a standalone C translation unit
-- (to be compiled against runtime/quant_runtime.{h,c}).
emitC :: [Bytecode] -> Either String Text
emitC bcs
  | FuncName "main" `notElem` map bytecodeFunction bcs =
      Left "native backend: program has no `main` function"
  | otherwise = do
      let userFns = Set.fromList (map bytecodeFunction bcs)
      funcs <- mapM (emitFunction userFns) bcs
      Right $
        T.unlines $
          [ "/* Generated by glados --native; do not edit. */",
            "#include \"quant_runtime.h\"",
            ""
          ]
            ++ map protoLine bcs
            ++ [""]
            ++ funcs
            ++ [ "int main(void) {",
                 "    " <> mangle (FuncName "main") <> "(0, (const QtValue *)0);",
                 "    return 0;",
                 "}"
               ]
  where
    protoLine bc =
      "static QtValue "
        <> mangle (bytecodeFunction bc)
        <> "(size_t argc, const QtValue *args);"

-- | C identifier for a Quant function name ('.' becomes "__").
mangle :: FuncName -> Text
mangle (FuncName n) = "qf_" <> T.concatMap mangleChar n
  where
    mangleChar '.' = "__"
    mangleChar c
      | isAscii c && isAlphaNum c = T.singleton c
      | otherwise = "_x" <> T.pack (show (ord c)) <> "_"

localName :: VarName -> Text
localName (VarName n) = "l_" <> T.concatMap mangleChar n
  where
    mangleChar '.' = "__"
    mangleChar c
      | isAscii c && isAlphaNum c = T.singleton c
      | otherwise = "_x" <> T.pack (show (ord c)) <> "_"

-- | C string literal with octal escapes for anything non-printable.
cString :: Text -> Text
cString t = "\"" <> T.concatMap esc t <> "\""
  where
    esc '"' = "\\\""
    esc '\\' = "\\\\"
    esc '\n' = "\\n"
    esc '\r' = "\\r"
    esc '\t' = "\\t"
    esc c
      | isAscii c && ord c >= 0x20 && ord c < 0x7f = T.singleton c
      | otherwise = octEsc c
    -- Encode as UTF-8 bytes, each as a fixed-width octal escape (safe
    -- against following digit characters, unlike hex escapes).
    octEsc c = T.concat [T.pack ("\\" ++ pad (showOct b "")) | b <- utf8Bytes (ord c)]
    pad s = replicate (3 - length s) '0' ++ s
    utf8Bytes cp
      | cp < 0x80 = [cp]
      | cp < 0x800 = [0xc0 + cp `div` 64, 0x80 + cp `mod` 64]
      | cp < 0x10000 =
          [0xe0 + cp `div` 4096, 0x80 + (cp `div` 64) `mod` 64, 0x80 + cp `mod` 64]
      | otherwise =
          [ 0xf0 + cp `div` 262144,
            0x80 + (cp `div` 4096) `mod` 64,
            0x80 + (cp `div` 64) `mod` 64,
            0x80 + cp `mod` 64
          ]

emitFunction :: Set.Set FuncName -> Bytecode -> Either String Text
emitFunction userFns bc = do
  let fname = bytecodeFunction bc
      instrs = bytecodeInstructions bc
      pool = bytecodeStrings bc
      poolName = "P_" <> mangle fname
      targets = Set.fromList (concatMap jumpTargets instrs)
      locals = nub (concatMap localsOf instrs)
  bodies <- mapM (emitInstr fname userFns poolName) (zip [0 ..] instrs)
  let numbered =
        [ (if Set.member i targets then "  I" <> T.pack (show i) <> ": ;\n" else "")
            <> body
          | (i, body) <- zip [(0 :: Int) ..] bodies
        ]
      poolDef
        | null pool = []
        | otherwise =
            [ "static const char *"
                <> poolName
                <> "[] = {"
                <> T.intercalate ", " (map cString pool)
                <> "};"
            ]
  Right $
    T.unlines $
      poolDef
        ++ [ "static QtValue " <> mangle fname <> "(size_t argc, const QtValue *args) {",
             "  (void)argc; (void)args;",
             "  QtValue st[" <> T.pack (show (length instrs + 8)) <> "];",
             "  size_t sp = 0;"
           ]
        ++ ["  QtValue " <> localName v <> " = qt_unit();" | v <- locals]
        ++ ["  (void)" <> localName v <> ";" | v <- locals]
        ++ [ "  for (size_t qi = argc; qi > 0; qi--) { st[sp++] = args[qi - 1]; }"
           ]
        ++ numbered
        ++ [ "  return qt_unit();",
             "}"
           ]

jumpTargets :: Instruction -> [Int]
jumpTargets (IJump (InstructionPointer t)) = [t]
jumpTargets (IJumpTrue (InstructionPointer t)) = [t]
jumpTargets (IJumpFalse (InstructionPointer t)) = [t]
jumpTargets _ = []

localsOf :: Instruction -> [VarName]
localsOf (ILoad v) = [v]
localsOf (IStore v) = [v]
localsOf _ = []

binOpName :: BinaryOp -> Text
binOpName op = case op of
  BOpAdd -> "QT_BOP_ADD"
  BOpSub -> "QT_BOP_SUB"
  BOpMul -> "QT_BOP_MUL"
  BOpDiv -> "QT_BOP_DIV"
  BOpMod -> "QT_BOP_MOD"
  BOpEq -> "QT_BOP_EQ"
  BOpNeq -> "QT_BOP_NEQ"
  BOpLt -> "QT_BOP_LT"
  BOpLte -> "QT_BOP_LTE"
  BOpGt -> "QT_BOP_GT"
  BOpGte -> "QT_BOP_GTE"
  BOpAnd -> "QT_BOP_AND"
  BOpOr -> "QT_BOP_OR"
  BOpBitAnd -> "QT_BOP_BITAND"
  BOpBitOr -> "QT_BOP_BITOR"
  BOpBitXor -> "QT_BOP_BITXOR"
  BOpShl -> "QT_BOP_SHL"
  BOpShr -> "QT_BOP_SHR"

unOpName :: UnaryOp -> Text
unOpName UOpNot = "QT_UOP_NOT"
unOpName UOpNeg = "QT_UOP_NEG"
unOpName UOpBitNot = "QT_UOP_BITNOT"

pushConst :: Text -> Text
pushConst expr = "  st[sp++] = " <> expr <> ";"

emitInstr :: FuncName -> Set.Set FuncName -> Text -> (Int, Instruction) -> Either String Text
emitInstr fname userFns poolName (idx, instr) = case instr of
  IPush v -> pushValue v
  IPop -> ok "  sp--;"
  IDup -> ok "  st[sp] = st[sp - 1]; sp++;"
  IBinary op ->
    ok $ "  st[sp - 2] = qt_binary(" <> binOpName op <> ", st[sp - 2], st[sp - 1]); sp--;"
  IUnary op ->
    ok $ "  st[sp - 1] = qt_unary(" <> unOpName op <> ", st[sp - 1]);"
  ILoad v -> ok $ "  st[sp++] = " <> localName v <> ";"
  IStore v -> ok $ "  " <> localName v <> " = st[--sp];"
  IJump (InstructionPointer t) -> ok $ "  goto I" <> T.pack (show t) <> ";"
  IJumpTrue (InstructionPointer t) ->
    ok $ "  if (qt_truthy(st[--sp])) goto I" <> T.pack (show t) <> ";"
  IJumpFalse (InstructionPointer t) ->
    ok $ "  if (!qt_truthy(st[--sp])) goto I" <> T.pack (show t) <> ";"
  ICall (FunctionRef target) argc -> ok (emitCall target argc)
  IRet -> ok "  return st[--sp];"
  INop -> ok "  ;"
  ICovMark _ -> ok "  ;"
  ICovBranch _ -> ok "  ;"
  INewArray -> ok "  st[sp++] = qt_array_new();"
  IArrayGet ->
    ok $
      "  { QtValue qidx = st[--sp]; QtValue qref = st[--sp];"
        <> " st[sp++] = qt_array_get(qref, qt_want_int(qidx, \"array index\")); }"
  IArrayGetOrNew ->
    ok $
      "  { QtValue qidx = st[--sp]; QtValue qref = st[--sp];"
        <> " st[sp++] = qt_array_get_or_new(qref, qt_want_int(qidx, \"array index\")); }"
  IArraySet ->
    ok $
      "  { QtValue qv = st[--sp]; QtValue qidx = st[--sp]; QtValue qref = st[--sp];"
        <> " qt_array_set(qref, qt_want_int(qidx, \"array index\"), qv); }"
  ICast CastToInt -> ok "  st[sp - 1] = qt_cast_int(st[sp - 1]);"
  ICast CastToFloat -> ok "  st[sp - 1] = qt_cast_float(st[sp - 1]);"
  ICast CastToBool -> ok "  st[sp - 1] = qt_cast_bool(st[sp - 1]);"
  ICast CastToString -> ok "  st[sp - 1] = qt_cast_string(st[sp - 1]);"
  other -> unsupported other
  where
    ok = Right
    unsupported i =
      Left $
        "native backend: unsupported instruction "
          ++ takeWhile (/= ' ') (show i)
          ++ " (in function `"
          ++ T.unpack (unFuncName fname)
          ++ "` at offset "
          ++ show idx
          ++ ")"
    pushValue v = case v of
      VInt n -> ok $ pushConst ("qt_int(INT64_C(" <> T.pack (show n) <> "))")
      VFloat f -> ok $ pushConst ("qt_float(" <> T.pack (showHFloat f "") <> ")")
      VBool True -> ok $ pushConst "qt_bool(1)"
      VBool False -> ok $ pushConst "qt_bool(0)"
      VStringRef i -> ok $ pushConst ("qt_string(" <> poolName <> "[" <> T.pack (show i) <> "])")
      VString s -> ok $ pushConst ("qt_string(" <> cString s <> ")")
      VUnit -> ok $ pushConst "qt_unit()"
      _ ->
        Left $
          "native backend: unsupported constant "
            ++ takeWhile (/= ' ') (show v)
            ++ " in function `"
            ++ T.unpack (unFuncName fname)
            ++ "`"
    emitCall target argc =
      let nText = T.pack (show argc)
          bufLen = T.pack (show (max 1 argc))
          gather =
            "QtValue ca["
              <> bufLen
              <> "];"
              <> " for (size_t qi = 0; qi < "
              <> nText
              <> "; qi++) { ca[qi] = st[--sp]; }"
          callExpr
            | Set.member target userFns = mangle target <> "(" <> nText <> ", ca)"
            | otherwise =
                "qt_call_builtin(" <> cString (unFuncName target) <> ", " <> nText <> ", ca)"
       in "  { " <> gather <> " st[sp++] = " <> callExpr <> "; }"
